In [1]:
from acquisition_function_net import *

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

In [ ]:
model_body = AcquisitionFunctionBodyPointnetV1and2(
    dimension=6, n_hist_out=1, n_acqf_params=0,
    
    history_enc_hidden_dims=[100, 100],
    pooling="max",
    encoded_history_dim=100,

    input_xcand_to_local_nn=True,
    input_xcand_to_final_mlp=False,
    
    activation_at_end_pointnet=True,
    layer_norm_pointnet=False,
    dropout_pointnet=None,
    activation_pointnet="relu",

    include_best_y=False,
    n_pointnets=1
)
model_body

In [6]:
dimension = 6
n_hist_out = 2
n_acqf_params = 3
af_body_init_params = dict(
    dimension=dimension,
    
    history_enc_hidden_dims=[100, 100],
    pooling="max",
    encoded_history_dim=100,

    input_xcand_to_local_nn=True,
    input_xcand_to_final_mlp=False,
    
    activation_at_end_pointnet=True,
    layer_norm_pointnet=False,
    dropout_pointnet=None,
    activation_pointnet="relu",

    include_best_y=False,
    n_pointnets=1)

# af_head_class = AcquisitionFunctionNetFinalMLP
# af_head_init_params = dict(
#     hidden_dims=[100, 100],
#     activation="relu",
#     layer_norm_before_end=False,
#     layer_norm_at_end=False,
#     dropout=None
# )

af_head_class = AcquisitionFunctionNetFinalMLPSoftmaxExponentiate
af_head_init_params = dict(
    hidden_dims=[100, 100],
    activation="relu",
    layer_norm_before_end=False,
    layer_norm_at_end=False,
    dropout=None,

    include_alpha=False,
    learn_alpha=False,
    initial_alpha=1.0,
    initial_beta=1.0,
    learn_beta=False,
    softplus_batchnorm=False,
    softplus_batchnorm_momentum=0.1,
    positive_linear_at_end=False,
    gp_ei_computation=False
)

af = TwoPartAcquisitionFunctionNetFixedHistoryOutputDim(
    output_dim=4,
    n_acqf_params=n_acqf_params,
    n_hist_out=n_hist_out,
    af_body_class=AcquisitionFunctionBodyPointnetV1and2,
    af_head_class=af_head_class,
    af_body_init_params=af_body_init_params,
    af_head_init_params=af_head_init_params,
    standardize_outcomes=False
)
print(af)

batch_size = 10
n_hist = 5
n_cand = 2
x_hist = torch.rand(batch_size, n_hist, dimension)
y_hist = torch.rand(batch_size, n_hist, n_hist_out)
x_cand = torch.rand(batch_size, n_cand, dimension)
acqf_params = torch.rand(batch_size, n_cand, n_acqf_params)
output = af(x_hist, y_hist, x_cand, acqf_params,
            exponentiate=True, softmax=False)
output

TwoPartAcquisitionFunctionNetFixedHistoryOutputDim(
  (af_body): AcquisitionFunctionBodyPointnetV1and2(
    (pointnet): PointNetLayer(
      (network): Dense(
        (0): Linear(in_features=17, out_features=100, bias=True)
        (1): ReLU()
        (2): Linear(in_features=100, out_features=100, bias=True)
        (3): ReLU()
        (4): Linear(in_features=100, out_features=100, bias=True)
        (5): ReLU()
      )
    )
  )
  (af_head): AcquisitionFunctionNetFinalMLPSoftmaxExponentiate(
    (dense): Dense(
      (0): Linear(in_features=100, out_features=100, bias=True)
      (1): ReLU()
      (2): Linear(in_features=100, out_features=100, bias=True)
      (3): ReLU()
      (4): Linear(in_features=100, out_features=4, bias=True)
    )
    (transform): SoftmaxOrSoftplusLayer(
      (softplus): Softplus(beta=1.0, threshold=20)
    )
  )
)


tensor([[[0.2038, 0.6025, 1.1998, 1.5677],
         [0.2973, 0.6669, 1.3373, 1.5000]],

        [[0.2254, 0.6487, 1.4972, 1.8132],
         [0.3017, 0.8433, 1.6667, 1.5163]],

        [[0.2062, 0.6810, 1.2439, 1.5903],
         [0.1585, 0.7847, 1.6275, 1.8296]],

        [[0.2769, 0.5962, 1.3208, 1.3376],
         [0.2787, 0.7981, 1.3617, 1.2185]],

        [[0.3030, 0.9892, 1.5803, 1.3891],
         [0.2133, 0.6847, 1.4985, 1.8892]],

        [[0.1719, 0.4849, 1.0633, 1.5968],
         [0.2634, 0.7327, 1.5219, 1.5877]],

        [[0.4226, 0.9686, 1.4642, 1.3840],
         [0.4266, 0.7479, 1.3515, 1.4704]],

        [[0.2633, 0.7499, 1.4845, 1.5628],
         [0.3249, 0.5934, 1.2837, 1.5457]],

        [[0.3124, 0.6943, 1.5168, 1.5647],
         [0.2528, 0.5837, 1.2725, 1.6169]],

        [[0.3476, 0.9063, 1.5148, 1.2070],
         [0.2386, 0.7481, 1.7169, 1.5389]]], grad_fn=<SoftplusBackward0>)

In [8]:
dimension = 6
n_acqf_params = 3
af_body_init_params = dict(
    dimension=dimension,
    
    history_enc_hidden_dims=[100, 100],
    pooling="max",
    encoded_history_dim=100,

    input_xcand_to_local_nn=True,
    input_xcand_to_final_mlp=False,
    
    activation_at_end_pointnet=True,
    layer_norm_pointnet=False,
    dropout_pointnet=None,
    activation_pointnet="relu",

    include_best_y=False,
    n_pointnets=1)
af_head_init_params = dict(
    hidden_dims=[100, 100],
    activation="relu",
    layer_norm_before_end=False,
    layer_norm_at_end=False,
    dropout=None
)
gittins_af = GittinsAcquisitionFunctionNet(
    af_class=TwoPartAcquisitionFunctionNetFixedHistoryOutputDim,
    variable_lambda=True,
    costs_in_history=True,
    cost_is_input=False,
    af_body_class=AcquisitionFunctionBodyPointnetV1and2,
    af_head_class=AcquisitionFunctionNetFinalMLP,
    af_body_init_params=af_body_init_params,
    af_head_init_params=af_head_init_params,
    standardize_outcomes=False
)
print(gittins_af)

gittins_af.save_init('test_ddd')

batch_size = 10
n_hist = 5
n_cand = 2
x_hist = torch.rand(batch_size, n_hist, dimension)
y_hist = torch.rand(batch_size, n_hist, 1)
log_cost_hist = torch.rand(batch_size, n_hist, 1)
x_cand = torch.rand(batch_size, n_cand, dimension)
log_lambda = torch.rand(batch_size, n_cand, 1)
output = gittins_af(x_hist, y_hist, x_cand,
                    lambda_cand=log_lambda,
                    cost_hist=log_cost_hist,
                    is_log=True)
output

GittinsAcquisitionFunctionNet(
  (base_model): TwoPartAcquisitionFunctionNetFixedHistoryOutputDim(
    (af_body): AcquisitionFunctionBodyPointnetV1and2(
      (pointnet): PointNetLayer(
        (network): Dense(
          (0): Linear(in_features=15, out_features=100, bias=True)
          (1): ReLU()
          (2): Linear(in_features=100, out_features=100, bias=True)
          (3): ReLU()
          (4): Linear(in_features=100, out_features=100, bias=True)
          (5): ReLU()
        )
      )
    )
    (af_head): AcquisitionFunctionNetFinalMLP(
      (dense): Dense(
        (0): Linear(in_features=100, out_features=100, bias=True)
        (1): ReLU()
        (2): Linear(in_features=100, out_features=100, bias=True)
        (3): ReLU()
        (4): Linear(in_features=100, out_features=1, bias=True)
      )
    )
  )
)


tensor([[[ 0.4667],
         [ 0.3615]],

        [[ 0.1217],
         [ 0.3055]],

        [[ 0.3452],
         [ 0.4369]],

        [[ 0.2177],
         [ 0.0614]],

        [[ 0.1412],
         [ 0.3216]],

        [[ 0.0997],
         [ 0.4380]],

        [[ 0.0273],
         [-0.3770]],

        [[ 0.2848],
         [ 0.0726]],

        [[ 0.3190],
         [-0.6046]],

        [[ 0.5430],
         [ 0.2411]]], grad_fn=<ViewBackward0>)

In [ ]:
n.get_info_dict()

In [ ]:
n.save_init("fold")

In [ ]:
from utils import SaveableObject
SaveableObject.load_init("fold")

In [ ]:
class _Dummy(nn.Module):
    def __init__(self, the_module):
        super().__init__()
        self.the_module = the_module
        self.register_forward_pre_hook(self._my_pre_forward_hook)
    
    @staticmethod
    def _my_pre_forward_hook(module, inputs):
        # do something
        return inputs_modified
    
    def forward(self, a, b, **kwargs):
        return self.the_module(a, b, **kwargs)

class MyModule(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()
        self._dummy = _Dummy()

    def forward(self, a, b=3, **kwargs):
        return self._dummy(a, b, **kwargs)

In [ ]:
d = {'a': 1, 'b': 2}
for k, v in d.items():
    if v == 1:
        d[k] = v + 1
d

In [ ]:
from nn_utils import SaveableObject
SaveableObject()

In [ ]:
from torch import nn
class Ta(nn.Module):
    pass
b = Ta()
b(4)

In [1]:
from utils import ei_helper_inverse
import torch
x = torch.tensor([2.0], requires_grad=True)
y = ei_helper_inverse(x)
y.backward()
print(x.grad)

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [4]:
from utils import gi_normal
import torch

c = torch.tensor([0.00001, 0.1])
mu = torch.tensor([-0.3, 0.2])
sigma = torch.tensor([1.7, 0.06])
gi_normal(c, mu, sigma)

tensor([6.5743, 0.1013])

In [61]:
from botorch.models.gp_regression import SingleTaskGP
from botorch.models.transforms.outcome import Log

batch = 4
n_hist = 5
d = 6
m = 2
model = SingleTaskGP(
    train_X=torch.rand(n_hist, d),
    train_Y=torch.rand(n_hist, m),
    outcome_transform=Log()
)
print(f"{model.batch_shape=}")

posterior = model.posterior(torch.rand(7, d))
print(f"{posterior.mean.shape=}, {posterior.variance.shape=}")
print(f"{posterior.mean[..., 0].shape=}")
print(f"{posterior.mean.squeeze(-1).shape=}")
posterior

model.batch_shape=torch.Size([])
posterior.mean.shape=torch.Size([7, 2]), posterior.variance.shape=torch.Size([7, 2])
posterior.mean[..., 0].shape=torch.Size([7])
posterior.mean.squeeze(-1).shape=torch.Size([7, 2])


/Users/aloja/opt/anaconda3/lib/python3.9/site-packages/botorch/models/utils/assorted.py:202: InputDataWarning: Input data is not standardized (mean = tensor([-1.3147, -1.7337]), std = tensor([2.3553, 0.9760])). Please consider scaling the input to zero mean and unit variance.
  warnings.warn(msg, InputDataWarning)


In [69]:
torch.rand([6,3]).unsqueeze(-1).shape

torch.Size([6, 3, 1])

In [73]:
import itertools

# Define your parameter dependencies
parameter_dependencies = {
    "gittins": {
        "normalize_gi_loss": [True, False],  # Only relevant for gittins
    },
    "another_method": {
        "a": ["value1", "value2"],
        "t": [1, 2, 3] # Relevant only for another_method
    },
    # Add more methods and their specific parameters as needed
}

# Generate the Cartesian product for each method
sweep_parameters = []
for method, params in parameter_dependencies.items():
    param_names, param_values = zip(*params.items())  # Extract names and values
    product = itertools.product(*param_values)  # Cartesian product of relevant values
    for combination in product:
        config = {"method": method}  # Base method
        config.update(dict(zip(param_names, combination)))  # Add dependent params
        sweep_parameters.append(config)

sweep_parameters

[{'method': 'gittins', 'normalize_gi_loss': True},
 {'method': 'gittins', 'normalize_gi_loss': False},
 {'method': 'another_method', 'a': 'value1', 't': 1},
 {'method': 'another_method', 'a': 'value1', 't': 2},
 {'method': 'another_method', 'a': 'value1', 't': 3},
 {'method': 'another_method', 'a': 'value2', 't': 1},
 {'method': 'another_method', 'a': 'value2', 't': 2},
 {'method': 'another_method', 'a': 'value2', 't': 3}]

In [4]:
from utils import SaveableObject

class C:
    def __new__(cls, *args, **kwargs):
        print(f"in C: {cls.__name__}.__new__({args}, {kwargs}) called")
        return super().__new__(cls)
    def __init__(self, b, **kwargs):
        print(f"{self.__class__.__name__}.__init__({b=}, {kwargs}) called")
    pass

class A(C, SaveableObject):
    # def __init__(self, b=4, **kwargs):
    #     print(f"{self.__class__.__name__}.__init__({b=}, {kwargs}) called")
    pass

a = A(32, a=4)
a.save_init("test")
b = A.load_init("test")

in C: A.__new__((32,), {'a': 4}) called
A.__init__(b=32, {'a': 4}) called
in C: A.__new__((), {'b': 32, 'a': 4}) called
A.__init__(b=32, {'a': 4}) called


In [7]:
class W(SaveableObject):
    pass

W.load_init("test")

TypeError: Trying to load a W instance but the JSON file contains a A instance. Instead of calling W.load_init, call SaveableObject.load_init  or A.load_init

In [8]:
SaveableObject.load_init("test")

in C: A.__new__((), {'b': 32, 'a': 4}) called
A.__init__(b=32, {'a': 4}) called


In [10]:
w=SaveableObject()

TypeError: Can't instantiate abstract class SaveableObject with abstract method __init__

In [3]:
A.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.A.__init__(self, b=4, **kwargs)>,
              '__doc__': None})

In [4]:
C.__dict__

mappingproxy({'__module__': '__main__',
              '__new__': <staticmethod at 0x7f77e981a880>,
              '__dict__': <attribute '__dict__' of 'C' objects>,
              '__weakref__': <attribute '__weakref__' of 'C' objects>,
              '__doc__': None})

In [5]:
class B: pass
B.__new__

<function object.__new__(*args, **kwargs)>